version: '3.3'
services:
  api:
    build: api
    environment:
      RESULTS_DATA_DIR: /data/results
    volumes:
      - ./data:/data

    # Expose port 8000 for connecting from outside of the Docker container
    ports:
      - "8000:8000"

  scheduler:
    build: scheduler
    environment:
      DATA_DIR: /data
    volumes:
      - ./data:/data
